### ISSUE TITLE
free(): invalid pointer error

### ISSUE THREAD

**Issue by TonyPuryer** [ElliotKillick/Mido#5]
Immediately aborts with the error:

*** glibc detected *** /bin/sh: free(): invalid pointer: 0x000cd0cc ***

Attempting to run it on an old nas with 'uname':
Linux Seagate-D2 3.10.72-svn18863 #1 Thu Jan 17 00:12:15 UTC 2019 armv7l GNU/Linux

Kernel & software is probably too deprecated?

**Comment by ElliotKillick** [comment]
Can you run: `ls -l /bin/sh` and `sh --version`

If your system is systemd then perhaps also `coredumpctl info` to get the last crash stack trace.

Does the script even print anything before that error occurs?

**Comment by TonyPuryer** [comment]
`ls -l /bin/sh`

**Comment by ElliotKillick** [comment]
Your BusyBox shell has broken POSIX compliance: https://pubs.opengroup.org/onlinepubs/009695299/utilities/trap.html#tag_04_146_14

I've confirmed that the issue has already been fixed in newer BusyBox versions. It looks to have been fixed in [`3 July 2017 -- BusyBox 1.27.0 (unstable)` with commit message `ash: fix 'trap - 65'`](https://busybox.net/). You're running 1.23 hence why you still have that bug (`2019` must be the build time?).

For this reason, I recommend you workaround the bug by simply adding this on the line before `signo=$((signo + 1))` in `Mido.sh`: `[ "$signo" = 64 ] && break`

I've fixed a few more POSIX compliance issues in regards to coreutils (e.g. replaced `fmt` with `fold`) so make sure to update and let me know if you can get it working now.

**Comment by TonyPuryer** [comment]
That fix worked, in that the download attempted to start, but now 'head' is giving troubles.

I installed a later version of Busybox, but still the same issue -

`head: invalid option -- '-'
BusyBox v1.36.1 (2023-09-01 19:09:45 UTC) multi-call binary.`

I understand if you would like to close this issue; I don't want to waste any more of your time seeking to shoehorn fixes for some ancient, obsolete NAS operating system.
